/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package centralized_sms;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import org.apache.xmlbeans.impl.xb.xsdschema.Public;

/**
 *
 * @author bernard.ndaruhutse
 */
public class Login extends javax.swing.JFrame {

        static Connection conn = null;   // initialize connection, Prepared statement and Resultset
        private PreparedStatement pst;
        private   ResultSet rs = null;


    
    /** Creates new form Login */
    public Login() {
           
           this.setResizable(false);
           this.setTitle("Login") ;          
           this.setUndecorated(true);
           this.setIcon();
                  
        initComponents();
        
             this.setTitle("Welcome to CSMS");
             this.setDefaultCloseOperation(3);
             this.setResizable(false);
             this.errortext_label.setVisible(false);
             this.username.setHorizontalAlignment(JTextField.CENTER);
             this.password.setHorizontalAlignment(JTextField.CENTER);
             
        conn = Db_Connection.connectDb();  // invoke connection class

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        loginbtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        errortext_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setForeground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        loginbtn.setBackground(new java.awt.Color(0, 102, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGIN");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        jButton_login.setBackground(new java.awt.Color(51, 153, 255));
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        errortext_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errortext_label.setForeground(new java.awt.Color(255, 255, 51));
        errortext_label.setText("......");

        javax.swing.GroupLayout loginbtnLayout = new javax.swing.GroupLayout(loginbtn);
        loginbtn.setLayout(loginbtnLayout);
        loginbtnLayout.setHorizontalGroup(
            loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginbtnLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(loginbtnLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(loginbtnLayout.createSequentialGroup()
                .addGroup(loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginbtnLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel5))
                    .addGroup(loginbtnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(loginbtnLayout.createSequentialGroup()
                .addGroup(loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginbtnLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(errortext_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginbtnLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginbtnLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginbtnLayout.setVerticalGroup(
            loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginbtnLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(errortext_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(loginbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/centralized_sms/imgs/product.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGEMENT  SYSTEM");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WELCOME TO");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CENTRALIZED STORE ");

        jSeparator1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(24, 24, 24))))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(loginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
                            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
   Login.this.Btn_Login_ActionPerformed(evt);

    }//GEN-LAST:event_jButton_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
            
        });
       
    }
    
   private void setIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("csms_store.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errortext_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_login;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginbtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void Btn_Login_ActionPerformed(ActionEvent evt) {
        
           try {
            String sql = "select a.username, a.password, a.role_name, b.first_name, c.dept_name, c.id as dpid  from users_info a left join staff_info b on a.staff_id = b.id left join department_info c on b.dept_id = c.id  where a.username = '" + this.username.getText() + "' and a.Password = '" + this.password.getText() + "'";
            pst = conn.prepareStatement(sql);
            this.rs = pst.executeQuery();
            if (this.rs.next()) {
                
                Dashboard dash ;
                String fname = this.rs.getString("first_name");
                String usrme = this.rs.getString("username");
                String role = this.rs.getString("role_name");
                String department_hod = this.rs.getString("dept_name");
                String dptid_hod = this.rs.getString("dpid");
                      
                dash = new Dashboard();

                if(role.equals("Administrator")){
                       dash.role_portal_txt.setText(role + " Panel");
                       dash.names_text_label1.setText(fname);
                      
                       dash.left_menu_storekeeper.setVisible(false);
                       dash.store_panel_requests.setVisible(false);
                       dash.store_panel.setVisible(false);
                       
                         
                       dash.left_menu_admin.setVisible(true);
                       dash.admin_panel_users.setVisible(false);
                       dash.admin_panel_store.setVisible(false);
                       dash.admin_panel_settings.setVisible(false);
                       dash.rnp_logo_home.setVisible(true);  
                       
                       dash.hod_panel_store.setVisible(false);  
                       dash.hod_panel_items_distribution.setVisible(false);  
                       dash.left_menu_hod.setVisible(false);  
                       
                       dash.senioradmin_panel_dash.setVisible(false);  
                       dash.left_menu_senioradmin.setVisible(false);  
                      
                       dash.setVisible(true);
                      this.dispose();

                 }
                 else if(role.equals("Storekeeper")){

                   
                      dash.role_portal_txt.setText(role + " Panel");
                      dash.names_text_label1.setText(fname);
                    
                 dash.left_menu_storekeeper.setVisible(true);
                 dash.store_panel_requests.setVisible(false);
                 dash.store_panel.setVisible(false);
               
                 dash.hod_panel_store.setVisible(false);  
                 dash.hod_panel_items_distribution.setVisible(false);  
                 dash.left_menu_hod.setVisible(false);  
                 
                 dash.senioradmin_panel_dash.setVisible(false);  
                 dash.left_menu_senioradmin.setVisible(false);  

                 dash.left_menu_admin.setVisible(false);
                 dash.admin_panel_users.setVisible(false);
                 dash.admin_panel_store.setVisible(false);
                 dash.admin_panel_settings.setVisible(false);
                 dash.rnp_logo_home.setVisible(true); 
                       dash.setVisible(true);
                       this.dispose();
                    
                  }
                 else if(role.equals("HOD")){
                 
                    dash.role_portal_txt.setText(role + " Panel");
                     dash.names_text_label1.setText(fname);
                     dash.jLabel_departmentname.setText(department_hod + " Department");
                     dash.jLabel_hod_department.setText(department_hod + " Department");
                     dash.jLabel_deptid.setText(dptid_hod);
                     dash.jLabeldeptid_hod.setText(dptid_hod);

                 dash.left_menu_storekeeper.setVisible(false);
                 dash.store_panel_requests.setVisible(false);
                 dash.store_panel.setVisible(false);
                
                 dash.hod_panel_store.setVisible(false);  
                 dash.hod_panel_items_distribution.setVisible(false);  
                 dash.left_menu_hod.setVisible(true);  
                 
                 dash.senioradmin_panel_dash.setVisible(false);  
                 dash.left_menu_senioradmin.setVisible(false);  

                 dash.left_menu_admin.setVisible(false);
                 dash.admin_panel_users.setVisible(false);
                 dash.admin_panel_store.setVisible(false);
                 dash.admin_panel_settings.setVisible(false);
                 dash.rnp_logo_home.setVisible(true); 
                       dash.setVisible(true);
                       this.dispose();    
                 
                 }
                 else if(role.equals("Senior Admin")){
                 
                 dash.role_portal_txt.setText(role + " Panel");
                 dash.names_text_label1.setText(fname);
                 
                 dash.jLabel_deprname_senior.setText(department_hod + " Department");

                 dash.left_menu_storekeeper.setVisible(false);
                 dash.store_panel_requests.setVisible(false);
                 dash.store_panel.setVisible(false);
                
                 dash.hod_panel_store.setVisible(false);  
                 dash.hod_panel_items_distribution.setVisible(false);  
                 dash.left_menu_hod.setVisible(false);  
                 
                 dash.senioradmin_panel_dash.setVisible(false);  
                 dash.left_menu_senioradmin.setVisible(true);  

                 dash.left_menu_admin.setVisible(false);
                 dash.admin_panel_users.setVisible(false);
                 dash.admin_panel_store.setVisible(false);
                 dash.admin_panel_settings.setVisible(false);
                 dash.rnp_logo_home.setVisible(true); 
                 
           
                 
                 
                       dash.setVisible(true);
                       this.dispose();    
                 
                     
                 
                 }
                   
                } else{
                
                this.errortext_label.setVisible(true);
                this.errortext_label.setText("Invalid Login Details !");
//                this.errortext_label.setForeground(Color.red);
            }
        }
        catch ( SQLException e) {
         JOptionPane.showMessageDialog(null, e.getMessage());

        }
     


        
    
    }
}


